"""Embed a small real catalogue sample for the isolated Open Design preview."""
import base64
import io
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[2]
source = (root / 'catalog-runtime-data.js').read_text(encoding='utf-8')
data, _ = json.JSONDecoder().raw_decode(source[source.index('{'):])
available = [item for item in data['items'] if (item.get('photos') or [''])[0].startswith('/assets/catalog-products/')]
selected = []
categories = set()
for item in available:
    category = item.get('public_category') or item.get('category')
    if category not in categories:
        selected.append(item)
        categories.add(category)
for item in available:
    if len(selected) >= 24:
        break
    if item not in selected:
        selected.append(item)
for item in selected:
    with Image.open(root / item['photos'][0].lstrip('/')) as image:
        image.thumbnail((420, 420))
        buffer = io.BytesIO()
        image.save(buffer, 'WEBP', quality=82)
    item['photos'] = ['data:image/webp;base64,' + base64.b64encode(buffer.getvalue()).decode('ascii')]
preview = {'site_url': data['site_url'], 'items': selected, 'routes': {'brands': {}, 'models': {}, 'categories': {}}}
loader = '''(() => {
  const isPreview = Boolean(window.KITRADE_PREVIEW_MODE)
    || window.location.protocol === "about:" || window.location.origin === "null";
  if (!isPreview) {
    document.write('<script src="' + new URL('catalog-runtime-data.js?v=4', document.currentScript.src).href + '"><\\/script>');
    return;
  }
  // Generated by scripts/catalog/build-design-preview.py; images work in srcdoc without a server.
  window.KITRADE_CATALOG_DATA = ''' + json.dumps(preview, ensure_ascii=False, separators=(',', ':')) + ';\n})();\n'
(root / 'catalog-data-loader.js').write_text(loader, encoding='utf-8')
print(f'Preview: {len(selected)} real products with embedded images, {len(loader.encode())} bytes')
